CREATE DATABASE IF NOT EXISTS admin_db;
USE admin_db;

CREATE TABLE Users (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(50) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  Role VARCHAR(20) DEFAULT 'staff',
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
